title:  Hang Jun Che's Homepage
page-top-title: Hang Jun Che
top-section-bg-text: College of Electronic and Information Engineering
home-subtitle: Hang Jun Che&ensp;|&ensp;车杭骏
copyright-text: 'Email: hjche123@swu.edu.cn'
